### PR TITLE
chore(build): add license information to POM file

### PR DESCRIPTION
**Pull request by mattgogerly**
Adds licensing information to generated POMs.

cc @link108 @dbyron-sf

### CODE REVIEW

**Comment by dbyron-sf** [comment]
Could you let us know the reason for this?  Also, can you post a before/after diff of the resulting pom?

**Comment by dbyron-sf** [comment]
related PR: https://github.com/spinnaker/clouddriver/pull/5423

If this is going to end up everywhere, I suspect https://github.com/spinnaker/spinnaker-gradle-project/tree/master/spinnaker-project-plugin is the place to put it.

**Comment by mattgogerly** [comment]
> Could you let us know the reason for this? Also, can you post a before/after diff of the resulting pom?

The reasoning is that corporate dependency procurement checks the POM file for Maven artifacts for the licensing information. If the license isn't found then manual intervention is required, meaning a load of tickets for every new version. By placing the license in the POM we bypass this.

Agree that would be the right place to put it, will open a PR there with a diff on Monday 👍

**Comment by dbyron-sf** [comment]
Sounds good.  Thanks!

**Pull request closed without merging**
