### PR TITLE
feat(huaweicloud): add a new provider of huaweicloud

### PR DESCRIPTION
**Pull request by zengchen1024**
This PR adds a new provider "Huawei Cloud" to supports new spinnaker/clouddriver#4176.
The cloud provider proposal is spinnaker/community#17.

### CODE REVIEW

**Comment by zengchen1024** [comment]
@marchello2000  Thanks very much for your reviewing!

**Comment by zengchen1024** [comment]
@Mergifyio refresh

**Comment by zengchen1024** [comment]
@marchello2000 Could you merge this pr? Thanks very much!

**Comment by marchello2000** [comment]
@zengchen1024 Sorry, i didn't see this, updated your branch, will merge when it passes

**Comment by zengchen1024** [comment]
@marchello2000 thanks very much!

**Pull request merged**
