### PR TITLE
fix(execution): Honor 'if stage fails' config for synthetic stages.

### PR DESCRIPTION
**Pull request by jtk54**

### CODE REVIEW

**Comment by jtk54** [comment]
Probably a good idea. Learning Kotlin tests real quick.

**Comment by marchello2000** [comment]
Thanks! much better than my https://github.com/spinnaker/orca/pull/2677, I will close my PR

**Comment by jtk54** [comment]
@marchello2000 Sounds good, sorry I didn't see your PR in the nifty github history thing.

**Comment by jtk54** [comment]
Added a test for this case.

**Comment by jtk54** [comment]
@spinnakerbot cherry-pick 1.12

**Pull request merged**
