### PR TITLE
gzip responses

### PR DESCRIPTION
**Pull request by anotherchrisberry**
a la:
https://github.com/spinnaker/clouddriver/blob/master/clouddriver-web/clouddriver-web.gradle#L34-L35
https://github.com/spinnaker/gate/blob/master/gate-web/gate-web.gradle#L28-L29

@ajordens or @robfletcher please review - did a quick smoke test locally and it works as expected

### CODE REVIEW

**Comment by cfieber** [comment]
There is a YAML configuration piece to this as well - I'm not sure just adding this dependency turns on gzip?

```
spring:
  http:
    gzip:
      vary: Accept-Encoding
      minGzipSize: 4096
      bufferSize: 16384
```

**Comment by anotherchrisberry** [comment]
I can add something to the YAML, but I did not add anything locally and responses are gzip'd with just this change:
screen shot 2016-02-12 at 3 24 48 pm
screen shot 2016-02-12 at 3 24 38 pm

**Comment by anotherchrisberry** [comment]
Digging in, it looks like the GzipFilter defaults are:
```yaml
  vary: Accept-Encoding, User-Agent
  minGzipSize: 256
  bufferSize: 8192
```
I can add the defaults you listed above to the clouddriver.yml if you think they are nicer defaults

**Comment by cfieber** [comment]
I'm fine with the builtin defaults, feel free to merge

**Pull request merged**
