### PR TITLE
bug(provider/openstack) - look up images by region for Openstack depl…

### PR DESCRIPTION
**Pull request by johnrengelman**
…oys.

I wanted to write a spec for this, but couldn't figure out the orca context layout that would be needed to do it. We validate this on a deployment though and it seems to fairly obvious change.

### CODE REVIEW

**Comment by johnrengelman** [comment]
@spinnaker-reviewers

**Comment by johnrengelman** [comment]
@spinnaker/reviewers

**Comment by edwinavalos** [comment]
If it passes before I have to be online I can merge it.

**Comment by johnrengelman** [comment]
passed. :)

**Comment by edwinavalos** [comment]
Oh wait I never got merge rights on Orca, good luck :p @johnrengelman

**Comment by johnrengelman** [comment]
@edwinavalos just :trollface:

**Pull request merged**
