### PR TITLE
core: Run jobs in parallel

### PR DESCRIPTION
**Pull request by lwander**
@duftler

### CODE REVIEW

**Comment by duftler** [comment]
LGTM.

**Comment by ajordens** [comment]
Just expressing some caution ... we're really trying to get away from this style of parallel stages in favor of making everything refId/requisiteRefId-based.

Guessing jobs are created as orchestrations and not pipelines?

**Comment by lwander** [comment]
The idea was to mirror the Deploy pipeline stage - how is that going to change?

**Comment by ajordens** [comment]
Thoughts are that eventually we'll only have a single way of running things
in parallel.

**Pull request merged**
