### PR TITLE
remove deprecated *Asg stages/tasks

### PR DESCRIPTION
**Pull request by anotherchrisberry**
**DO NOT MERGE BEFORE 5/5/16**

I migrated all pipelines that were using these stages to use the non-deprecated versions. I will work on getting script users moved over next week.

### CODE REVIEW

**Comment by tomaslin** [comment]
it's after 5/5/16, can this be merged?

**Comment by anotherchrisberry** [comment]
A great question only @ajordens the analytics wizard can answer

**Comment by ajordens** [comment]
http://atlasui.prod.netflix.net/ui/graph?backend=http:%2F%2Fatlas-main.us-west-1.prod.netflix.net:7001&g.q=name,task.invocations,:eq,nf.cluster,orca-main,:eq,:and,stageType,.*Asg,:re,:and,:sum,(,stageType,),:by,$(stageType),:legend,:stack&g.title=orca-main%2520individual%2520stage%2520invocation%2520counts&g.s=e-3h&g.e=now&g.tz=US%2FPacific&g.no_border=1&g.w=1593&g.h=249&g.layout=iw&g.l=0&g.ylabel=requests%2520per%2520second&g.refresh=1464066589220&mode=png&vsplit=520px&sel=expr.0.0&tagHeights.appClusterAsgs=104&tagHeights.name=104&tagHeights.stageType=104&tagFilters.stageType=.*Asg

Looks like theres still some usage ... notably copyLastAsg/destroyAsg/resizeAsg.

**Comment by anotherchrisberry** [comment]
**DO NOT MERGE BEFORE 6/5/16**

**Comment by dzapata** [comment]
The metric is now 0, safe to merge?

**Comment by anotherchrisberry** [comment]
@dzapata nope, sorry, we migrated Spinnaker a different account, so that URL is not quite valid

**Pull request closed without merging**
