### PR TITLE
fix(docs): publish docs to spinnaker.io since spinnaker.github.io is …

### PR DESCRIPTION
**Pull request by dbyron-sf**
…archived

### CODE REVIEW

**Review by brian-armory — APPROVED** [review]
LGTM. This is the correct directory. 

I think we'lll also need  a PR in the docs repo that creates an `_index.md` file so that there's a landing page like the old site: 
image

**Comment by dbyron-sf** [comment]
Thanks @brian-armory .  Would you mind creating that docs PR?

**Comment by dbyron-sf** [comment]
Also @brian-armory is this OK to go in before that docs PR?

**Comment by brian-armory** [comment]
This can be merged before the docs PR. It just wont display in the nav. It'll still be reachable if someone enters the URL

**Comment by dbyron-sf** [comment]
Thanks @brian-armory, here goes...

**Pull request merged**
