### PR TITLE
core/bake: Don't strip extraneous attributes from bake requests sent to Netflix's internal bakery.

### PR DESCRIPTION
**Pull request by duftler**
core/bake: Temporarily comment-out logic that strips extraneous attributes from bake requests sent to Netflix's internal bakery.

### CODE REVIEW

**Comment by duftler** [comment]
@tomaslin As discussed, this PR is just for use in running a test against the internal bakery.

**Comment by tomaslin** [comment]
Verified changes with our internal bakery and they have made changes so the requests are correctly going through. Please do not merge this code until we get confirmation that internal bakery has new ES schema.

**Comment by duftler** [comment]
@tomaslin This PR is ready. Please merge once the internal bakery is ready.

**Comment by duftler** [comment]
Will re-open a PR with these same changes.

**Pull request merged**
