### PR TITLE
core: In DeploymentDetailsAware, filter on CloudProvider/CloudProvide…

### PR DESCRIPTION
**Pull request by duftler**
…rType.

### CODE REVIEW

**Comment by duftler** [comment]
@lwander please review.
@tomaslin @cfieber @ajordens please review as well (hoping someone can sanity check this to ensure there is no negative effect on container image lookup).

**Comment by duftler** [comment]
Rebased.

**Comment by lwander** [comment]
LGTM

**Comment by tomaslin** [comment]
This LGTM for titus

**Pull request merged**
