### PR TITLE
feat(pipeline_templates): Support jinja expressions in source field

### PR DESCRIPTION
**Pull request by jervi**
Add support for recursively supporting jinja expressions in the source field of DCD templates. Currently, only the top level template definition supports jinja in the source field.

### CODE REVIEW

**Comment by jervi** [comment]
Upstream PR: https://github.com/spinnaker/orca/pull/1586

**Comment by jervi** [comment]
@spinnaker/reviewers PTAL

**Comment by robzienert** [comment]
I've mixed feelings on this. By introducing `Renderer` into the template loader process, we're tightly coupling a v1 schema concept (jinja rendering) to `TemplateLoader`, which may not be a concept in future schema implementations.

**Comment by jervi** [comment]
Do you have an idea of how this can be solved without using the renderer inside `TemplateLoader`? Or is dynamic sources in templates just not supposed to be supported?

**Comment by robzienert** [comment]
Dynamic sources were never intended to be supported. Dynamicism in this regard can nerf the ability for the publish template stage to perform pre-emptive plans as well as cascading pipeline saves (necessary for propagating some configs defined in templates to their concrete configs).

What's your use case that you need to have such dynamic behavior in templates?

**Comment by gardleopard** [comment]
We will experiment with shim pipelines to see if that can solve this for us. We will test that on Monday.

**Pull request closed without merging**
