### PR TITLE
chore(bakeManifest): Update BakeManifest error when missing expectedArtifact

### PR DESCRIPTION
**Pull request by justinrlee**
The default error message here is confusing.  This is purely a clarification to the error message.

### CODE REVIEW

**Comment by justinrlee** [comment]
I'm ignoring the commit title bot, cause we do squash merges anyways, I think.

**Comment by justinrlee** [comment]
@Mergifyio backport release-1.18.x

**Comment by justinrlee** [comment]
@Mergifyio backport release-1.19.x

**Comment by justinrlee** [comment]
Darn.  @ezimanyi thanks for merging!  What's the process to get this backported to 1.18 and 1.19?

**Comment by ezimanyi** [comment]
Hm, I'm not sure why this isn't working...I'll run the commands for now but will see if I can figure out why mergify isn't letting you.

**Comment by ezimanyi** [comment]
@Mergifyio backport release-1.19.x release-1.18x

**Comment by ezimanyi** [comment]
@Mergifyio backport release-1.18.x

**Comment by kevinawoo** [comment]
@mergifyio backport release-1.19.x

**Pull request merged**
