### PR TITLE
fix(pipeline): Bring back template validation messages in Deck

### PR DESCRIPTION
**Pull request by jervi**
Template validation errors are supposed to bubble up to the surface, but this broke in #3835. This PR brings them back.

Before:
image

After:
image

### CODE REVIEW

**Comment by jervi** [comment]
@spinnaker/oss-reviewers PTAL

**Comment by jervi** [comment]
@marchello2000 🙏

**Comment by jervi** [comment]
@spinnaker/oss-reviewers Anyone?

**Review by karmacoma-eth — APPROVED** [review]

**Comment by jervi** [comment]
@Mergifyio update

**Review by mattgogerly — APPROVED** [review]

**Review by christopherthielen — APPROVED** [review]

**Pull request merged**
