### PR TITLE
Get deploy task to look at previous stage output for AMI before using…

### PR DESCRIPTION
**Pull request by robfletcher**
… one from global context

This should prevent problems with pipelines that have parallel bake deploys of things in the same region (e.g. multiple git branches) where there's potential for the deploy to pick the wrong AMI from deployment details

@ajordens you should probably eyeball this since we were discussing it the other day.

### CODE REVIEW

**Comment by cfieber** [comment]
LGTM after a squash and rebase

**Comment by robfletcher** [comment]
You want me to squash & force push?

**Comment by cfieber** [comment]
yes please

**Comment by robfletcher** [comment]
Merged in 09f59688406e6d291cd21f50ee27879e45133cab

**Pull request closed without merging**
