### PR TITLE
Consider STOPPED stages and SUCCEEDED pipelines as `complete` rather than…

### PR DESCRIPTION
**Pull request by ajordens**
… `failed` when it comes to recording events (and sending notifications)

### CODE REVIEW

**Comment by ajordens** [comment]
PTAL @tomaslin -- Few bugs filed around notifications being send when a pipeline ends up in STOPPED (ie. Check Precondition or Manual Judgment w/ failPipeline = false).

**Comment by tomaslin** [comment]
this will send out a complete notification. Is this the right behavior? Or do we treat it as something that has been canceled in the echo end? https://github.com/spinnaker/echo/blob/master/echo-notifications/src/main/groovy/com/netflix/spinnaker/echo/notification/AbstractEventNotificationAgent.groovy#L70

**Comment by tomaslin** [comment]
also this will caused downstream pipelines to run if set as a trigger

**Comment by ajordens** [comment]
In reality, right now a stage would get an executionStatus of `STOPPED` but the execution will get `SUCCEEDED`. 

The difference being that the ExitStatus is not COMPLETED hence always sending a failure notice.

The downstream pipeline triggering is interesting. Given that we already treat the pipelines as SUCCEEDED than it would be consistent to also trigger downstream ... especially since a decision was made to not fail the pipeline.

**Comment by ajordens** [comment]
This PR doesn't actually change the behavior of the `DependentPipelineExecutionListener` so I'm going to merge this down.

However, there is something to be said about differentiating between executions that got to a leaf stage vs. those that short circuited. Should we ever need to do that, I could see modifying the `ExecutionPropagationListener` and having it flag the execution as being short circuited.

**Comment by anotherchrisberry** [comment]
Seems reasonable to me.

**Comment by anotherchrisberry** [comment]
Ahem LGTM

**Pull request merged**
