### PR TITLE
fix(provider/cf): fix form based manifest resolution in deploy stage (#3752)

### PR DESCRIPTION
**Pull request by zachsmith1**
Please see https://github.com/spinnaker/orca/pull/3752. 

Here is the breaking [commit](https://github.com/spinnaker/orca/commit/98152c833631a84203f700099149c955e4e4cbb1#diff-9c8b0013a03ef69b40307d50445a4acd)

The object mapping on line 50 was expecting an Artifact or/and an ArtifactId. The original was an actual manifest so it didn't map correctly. This would work fine with any deployments that weren't form based but all form based broke after this change. The new change uses the original working mapper wrapped in a method to add some error handling and more specific throwables. 

Co-authored-by: Zach Smith
Co-authored-by: Zach Smith
Co-authored-by: mergify[bot] <37929162+mergify[bot]@users.noreply.github.com>

### CODE REVIEW

**Comment by maggieneterval** [comment]
@zachsmith1 @german-muzquiz release manager approval is required to merge changes to release branches; adding @ethanfrogers as a reviewer.

Since this PR was opened prior to the publication of the new [cherry-pick criteria](https://www.spinnaker.io/community/contributing/releasing/#release-branch-patch-criteria), leaving it up to @ethanfrogers to merge at his discretion, but just wanted to highlight the new requirements for the future. Thanks!

**Comment by german-muzquiz** [comment]
Ah, good to know the criteria for cherry picks, thanks!

**Comment by zachsmith1** [comment]
Added regression comments in the description above.

**Comment by kevinawoo** [comment]
It would be great if there's a test to make sure the regression doesn't happen again ❤️ ❤️

**Pull request merged**
