### PR TITLE
(core) allow limit parameter when retrieving tasks

### PR DESCRIPTION
**Pull request by anotherchrisberry**
We have this functionality on pipelines, and we already propagate the `limit` parameter from Gate - we just ignore it.

@ajordens PTAL

### CODE REVIEW

**Comment by ajordens** [comment]
I think you need something like

**Comment by anotherchrisberry** [comment]
I think you're right so I added it.

**Comment by ajordens** [comment]
Needs a rebase

**Comment by anotherchrisberry** [comment]
Added some tests, will merge in the morning

**Pull request merged**
