### PR TITLE
Remove wildstar in call to cached jobs

### PR DESCRIPTION
**Pull request by lwander**
@ttomsu PTAL

https://github.com/spinnaker/fiat/issues/116

### CODE REVIEW

**Comment by ttomsu** [comment]
LGTM

**Comment by lwander** [comment]
Build failed due to JAVA HOME not being set - looks like it's part of a bigger issue with Travis

**Comment by ttomsu** [comment]
Ready to go now?

**Comment by lwander** [comment]
Yup just finished rebasing

**Pull request merged**
