### PR TITLE
add bulkUpsertEntityTags stage

### PR DESCRIPTION
**Pull request by anotherchrisberry**
Depends on https://github.com/spinnaker/clouddriver/pull/1426

### CODE REVIEW

**Comment by robzienert** [comment]
👍

**Comment by ajordens** [comment]
Do we need a bulk upsert task ... vs `gate` just sending over a single orchestration with multiple `upsertEntityTags` operations in it?

**Comment by anotherchrisberry** [comment]
I think, for performance reasons, we don't want to send over individual `upsertEntityTags` operations, since they'll either
 * (a) run serially, and each take ten seconds (since the first won't finish before the monitor completes, and that has been dialed back to 10 seconds), or
 * (b) run in parallel, and potentially clobber each other, as Clouddriver reads from Front50, then performs the write

For a job that wants to submit 24,000 tags, it'll be brutal (~3 days).

**Comment by ajordens** [comment]
(b) only happens if it's the same entity that's being tagged right?

So we're looking to tag many thousands of entities concurrently? If so, than the optimization makes sense ... and if we're doing the optimization we might as well remove the original `upsertEntityTags` task at some point and just funnel everything through the optimized bulk call?

**Comment by anotherchrisberry** [comment]
We were seeing the scenario you were describing in testing today - the user was submitting multiple tags to the same entity. The workaround was to wait a couple of seconds between each write (which is largely driving the work here).

Agree that we should consider deprecating the `upsertEntityTags` call once we get the `batch` operating smoothly.

**Comment by ajordens** [comment]
Yup ... submitting multiple tags to the same entity in parallel would be problematic ... if you know that multiple tags are needed, best to submit them all in a single api call ...

**Pull request merged**
