### PR TITLE
Precondition expressions no longer need to be wrapped in ${ and }

### PR DESCRIPTION
**Pull request by ajordens**
- The ExpressionPreconditionTask will explicitly evaluate the expression at task execution time
- Any portions of the expression wrapped in ${ and } will be evaluated at both pipeline start and stage start

### CODE REVIEW

**Comment by ajordens** [comment]
PTAL @tomaslin, this should be what we were talking about earlier today.

I'll update `deck` to remove any mention of ${ and }.

**Comment by tomaslin** [comment]
would probably add trigger and execution to the lookup to be consistent, otherwise LGTM https://github.com/spinnaker/orca/blob/1228f97803e0ca79fcb9ad2ce66132d509c27b23/orca-core/src/main/groovy/com/netflix/spinnaker/orca/batch/ExecutionContextManager.groovy#L77-L82

**Comment by ajordens** [comment]
I've rebased and added trigger/execution to the context.

**Comment by tomaslin** [comment]
LGTM

**Pull request merged**
