### PR TITLE
Fix(manifest): Fix manifests resolved by Spel

### PR DESCRIPTION
**Pull request by edgarulg**
**Issue Summary**
The way an array of manifests passed into a pipeline as YAML using `Spel` is getting mapped changed from v1.21.5 to v1.22.0.  In v1.21, the manifests resolved by a `Spel` function are flattened to have a list of manifests. In v1.22, the manifest are not flattened so it throws a `java.lang.IllegalArgumentException` exception.

The behavior changed because this fix: https://github.com/spinnaker/kork/pull/720

**Steps to reproduce**
switch spinnaker to 1.22 or higher, execute the following stage:
```json
{
  "account": "kubernetes",
  "cloudProvider": "kubernetes",
  "manifests": [
    "${#yamlFromUrl(\"https://raw.githubusercontent.com/dmrogers7/spinnaker-issues/main/manifests/array-of-manifests.yaml\")}"
  ],
  "moniker": {
    "app": "bugs-reproduced"
  },
  "name": "Deploy (Manifest)",
  "skipExpressionEvaluation": false,
  "source": "text",
  "trafficManagement": {
    "enabled": false,
    "options": {
      "enableTraffic": false,
      "services": []
    }
  },
  "type": "deployManifest"
}
```
**About the fix**
This issue only happen when the manifest uses `Spel` function to get the manifests and it return a list. Before the fix on kork, `Spel` flattening the list so it ensure that the `ResolveDeploySourceManifestTask` received only a list of manifest. Now the flattening logic is gone so when execute `#yamlFromUrl` it unmarshal the yaml and pass thru `ResolveDeploySourceManifestTask` as it is. This break the models because it expect a list of manifest and it's possible to get a nested list at this point. The following link has an example yaml that shows the below issue: https://github.com/dmrogers7/spinnaker-issues/blob/main/manifests/array-of-manifests.yaml

I included test to show the current behavior, then I just flattened the nested lists in the manifests before it is map to `DeployManifestContext` because this is something specific for the `ResolveDeploySourceManifestTask`

### CODE REVIEW

**Review by blaquezzz — APPROVED** [review]

**Review by german-muzquiz — APPROVED** [review]
Thanks for fixing this!

**Comment by link108** [comment]
@mergifyio backport release-1.22.x release-1.23.x release-1.24.x

**Comment by edgarulg** [comment]
@spinnakerbot add-label backport-candidate

**Comment by fieldju** [comment]
@edgarulg backport PR for 1.23.x is failing its build
https://github.com/spinnaker/orca/pull/4040

**Comment by edgarulg** [comment]
@fieldju the build for 1.23.x #4040 is failing with a integration test due to a timeout, My changes didn't touch the logic of the PreconfiguredJob test but I will increase the timeout and track.

**Comment by fieldju** [comment]
> @fieldju the build for 1.23.x #4040 is failing with an integration test due to a timeout, My changes didn't touch the logic of the PreconfiguredJob test but I will increase the timeout and track.

@edgarulg I will re-run the failed job and see if passes then.

**Comment by jeid64** [comment]
Is there any workaround in the meantime we can use? We just upgraded to Spinnaker 1.24.3 and our Kubernetes deploy pipelines are broken. We create a JSON manifest as a Property in a Propertyfile produced by Jenkins and then read the manifest in

```
  "manifests": [
    "${ #readJson(#stage( 'Build Kubernetes Manifests' )['context']['MANIFEST'])}"
  ],
```

which causes this exception
```
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.util.LinkedHashMap<java.lang.Object,java.lang.Object>` out of START_ARRAY token at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: com.netflix.spinnaker.orca.clouddriver.tasks.manifest.DeployManifestContext$DeployManifestContextBuilder["manifests"]->java.util.ArrayList[0]) at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59) at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1468) at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1242) at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:373) at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:29) at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:291) at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:250) at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27) at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeSetAndReturn(MethodProperty.java:158) at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.vanillaDeserialize(BuilderBasedDeserializer.java:274) at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserialize(BuilderBasedDeserializer.java:198) at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4453) at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2696) at com.netflix.spinnaker.orca.pipeline.model.StageExecutionImpl.mapTo(StageExecutionImpl.java:591) ... 37 more ",
```

Otherwise we have to wait for the next Orca release?

**Pull request merged**
