### PR TITLE
Fixes ./gradlew startup issue with proper fix. 

### PR DESCRIPTION
**Pull request by ttomsu**
Closes https://github.com/spinnaker/spinnaker/issues/1166

@duftler @jtk54 PTAL

### CODE REVIEW

**Comment by duftler** [comment]
LGTM.

**Comment by ttomsu** [comment]
@veeresh1982 Can you give this PR a test drive and confirm Orca still starts up for you?

**Comment by jtk54** [comment]
Tested startup locally, startup worked as intended.

**Comment by jtk54** [comment]
LGTM

**Pull request merged**
