### PR TITLE
fix(notifications): Propagate auth for application notifications

### PR DESCRIPTION
**Pull request by jervi**
Application and pipeline level notifications fails for protected apps, because orca is not propagating authentication to front50. That's sad if you want both security _and_ notifications. But I'm pleased to announce that with this PR, you can have your cake AND eat it too.

Root cause is https://github.com/spinnaker/front50/pull/408 (@ajordens FYI)

### CODE REVIEW

**Comment by jervi** [comment]
Don’t merge this yet. We discovered a problem with some pipeline executions. I’ll update the PRthis

**Comment by ajordens** [comment]
Ahh yes.

Let me know if you need a hand verifying any of this.

**Comment by jervi** [comment]
The problem we had was because of a mismatch between the orca version and the echo version, and was unrelated to these changes. So this is ready to be merged if it is approved.

**Comment by ajordens** [comment]
Thanks for the fix @jervi!

**Pull request merged**
