### PR TITLE
core: Send 'region=$region' to clouddriver operations instead of 'reg…

### PR DESCRIPTION
**Pull request by duftler**
…ions=[$region]'.

### CODE REVIEW

**Comment by duftler** [comment]
Tested with all manner of AWS and GCE ad-hoc and pipeline operations.
Should be no breaking changes as it will tolerate deck sending both regions/region and zones/zone.

**Comment by duftler** [comment]
@cfieber or @ajordens please review.

**Comment by cfieber** [comment]
LGTM, nice cleanup

**Comment by ajordens** [comment]
Tidy!

**Pull request merged**
