### PR TITLE
feat(mahe): Adding a gutenberg stage

### PR DESCRIPTION
**Pull request by jeyrschabu**
- Initial gutenberg stage
- Supports publishing with file upload

### CODE REVIEW

**Comment by anotherchrisberry** [comment]
Might make more sense to put this in our internal repo. 

(the existing property stages should probably move there, too, just have never gotten around to it)

**Comment by jeyrschabu** [comment]
Supports a direct publish to a topic with a post to the `/tasks` with the following payload:
```
{
	"job": [
		{
		 "type": "gutenbergPublish",
		 "env": "test",
		 "dataPointer":{
				"topic":"testTopic",
				"version":"2017-10-20T04:41:55.239Z",
				"repo":"direct",
				"hasMetaData":false,
				"hasContent":true,
				"dataString":"{\n   \"hello\" : \"world\"\n}"
		 },
		 "chunking":{
				"cass":{
					 "chunkingThreshold":"1048576",
					 "chunkSize":"262144"
				},
				"s3":{
					 "chunkingThreshold":"104857600",
					 "chunkSize":"10485760"
				}
		 },
		 "fastPropAttrs":{
				"serverId":"",
				"asg":"",
				"ami":"",
				"cluster":"",
				"appId":"testapp",
				"stack":"",
				"zone":"",
				"region":"",
				"ttl":""
		 },
		 "s2id":{
				"autogen1":""
		 },
		 "purgePolicy":{
				"minNumOfVersions":"10",
				"maxNumOfVersions":"10"
		 },
		 "contentSource":"stringText",
		 "stringText":"ewogICAiaGVsbG8iIDogIndvcmxkIgp9",
		 "updatedBy":"test@test.com"
		}
	],
	"application": "testapp",
	"description": "simple gutenberg direct publish"
}
```

Additionally, a local file can be uploaded as part of the publish:

```
{
	"job": [
		{
		 "type": "gutenbergPublish",
		 "env": "test",
		  "dataPointer":{
      "topic":"testTopic",
      "version":"2017-11-04T10:38:54.248Z",
      "repo":"s3",
      "bucket":"s3bucketname",
      "object":"s3Object",
      "hasMetaData":true,
      "hasContent":true
		 },
		 "chunking":{
				"cass":{
					 "chunkingThreshold":"1048576",
					 "chunkSize":"262144"
				},
				"s3":{
					 "chunkingThreshold":"104857600",
					 "chunkSize":"10485760"
				}
		 },
		 "fastPropAttrs":{
				"serverId":"",
				"asg":"",
				"ami":"",
				"cluster":"",
				"appId":"testapp",
				"stack":"",
				"zone":"",
				"region":"us-east-1",
				"ttl":""
		 },
		 "s2id":{
				"autogen1":""
		 },
		 "purgePolicy":{
				"minNumOfVersions":"10",
				"maxNumOfVersions":"10"
		 },
		 "metaData":{
				"expireTime":"9999-12-31T23:59:59.999Z",
				"compressAlgo":"none",
				"comment":""
		 },
		 "source" : "file:///Users/jchabu/Desktop/everything/essentials/notes/helloworld.json",
   	 "contentSource":"localFile",
		 "updatedBy": "test@test.com"
		}
	],
	"application": "testapp",
	"description": "simple gutenberg publish with a file"
}
```

**Comment by jeyrschabu** [comment]
@anotherchrisberry agreed.

**Comment by jeyrschabu** [comment]
[DO NOT MERGE]. Moving to internal repo

**Pull request closed without merging**
