### PR TITLE
fix(tasks): Fix MonitorKayentaCanaryTask on results data map

### PR DESCRIPTION
**Pull request by OscarMichelH**
Issue: Stage execution fails for Canary Analysis pulling metrics. Object Mapper used not support directly Instant datatype
image

Solution applied:
Orca handle the json response with different object mappers, the desired is use OrcaObjectMapper class, but override the default object mapper for entire pipelines TaskResult could affect other kind of stages/task results, so only data type Instant unsupported was changed before being returned.

### CODE REVIEW

**Comment by OscarMichelH** [comment]
Issue: Stage execution fails for Canary Analysis pulling metrics. Object Mapper used not support directly Instant datatype
image

Solution applied:
Orca handle the json response with different object mappers, the desired is use OrcaObjectMapper class, but override the default object mapper for entire pipelines TaskResult could affect other kind of stages/task results, so only data type Instant unsupported was changed before being returned.

**Comment by dbyron-sf** [comment]
Thanks much for this!  Do you mind waiting until spring boot 2.4 works with kayenta before we merge this?  See e.g. https://github.com/spinnaker/kayenta/pull/912.

**Comment by OscarMichelH** [comment]
> Thanks much for this! Do you mind waiting until spring boot 2.4 works with kayenta before we merge this? See e.g. [spinnaker/kayenta#912](https://github.com/spinnaker/kayenta/pull/912).

Okey once the spring boot bump has occurred we can verify that your PR is still good with it

**Comment by dogonthehorizon** [comment]
@dbyron-sf what's the motivation to hold until the spring boot upgrade? What's left before merging that PR, fixing up the integration tests?

**Comment by dbyron-sf** [comment]
> @dbyron-sf what's the motivation to hold until the spring boot upgrade? What's left before merging that PR, fixing up the integration tests?

I don't want to hold it up at all...but it's broken and needs code changes to fix...See for example [this job](https://github.com/spinnaker/kayenta/actions/runs/3275931718/jobs/5391386187) which fails with something like:
```
> Task :kayenta-orca:compileJava
/Users/dbyron/src/spinnaker/kayenta/kayenta-orca/src/main/java/com/netflix/kayenta/orca/controllers/PipelineController.java:34: error: cannot find symbol
import org.springframework.boot.actuate.health.CompositeHealthIndicator;
                                              ^
  symbol:   class CompositeHealthIndicator
  location: package org.springframework.boot.actuate.health
/Users/dbyron/src/spinnaker/kayenta/kayenta-orca/src/main/java/com/netflix/kayenta/orca/controllers/PipelineController.java:36: error: cannot find symbol
import org.springframework.boot.actuate.health.HealthAggregator;
                                              ^
  symbol:   class HealthAggregator
  location: package org.springframework.boot.actuate.health
/Users/dbyron/src/spinnaker/kayenta/kayenta-orca/src/main/java/com/netflix/kayenta/orca/controllers/PipelineController.java:38: error: cannot find symbol
import org.springframework.boot.actuate.health.HealthIndicatorRegistry;
                                              ^
  symbol:   class HealthIndicatorRegistry
  location: package org.springframework.boot.actuate.health
/Users/dbyron/src/spinnaker/kayenta/kayenta-orca/src/main/java/com/netflix/kayenta/orca/controllers/PipelineController.java:70: error: cannot find symbol
      HealthIndicatorRegistry healthIndicators,
      ^
  symbol:   class HealthIndicatorRegistry
  location: class PipelineController
/Users/dbyron/src/spinnaker/kayenta/kayenta-orca/src/main/java/com/netflix/kayenta/orca/controllers/PipelineController.java:71: error: cannot find symbol
      HealthAggregator healthAggregator,
      ^
  symbol:   class HealthAggregator
  location: class PipelineController
5 errors

> Task :kayenta-orca:compileJava FAILED
```

**Comment by OscarMichelH** [comment]
https://github.com/spinnaker/kayenta/commit/4067746b6b91dbc402f305d3cb594f11a329f8a7 was solved. Can we continue with this change?

**Review by dbyron-sf — APPROVED** [review]

**Comment by dbyron-sf** [comment]
@mergifyio backport release-1.27.x release-1.28.x release-1.29.x

**Pull request merged**
