### PR TITLE
chore(dependencies): Merging Keiko back into Orca

### PR DESCRIPTION
**Pull request by robzienert**
Keeping history. This would mean we'd be able to deprecate the keiko repo.

### CODE REVIEW

**Comment by jonsie** [comment]
I wonder if it would make sense to have an `orca-keiko` project that is itself multi-project for the various keiko modules?

**Comment by robzienert** [comment]
Why?

**Comment by jonsie** [comment]
I think all it would really achieve is providing a root for keiko in orca (for things like docs, primarily).  Probably not necessary.

**Comment by robzienert** [comment]
I had just put the docs into `keiko-core`. I'm not sure I want to get into the business of nested subprojects at this point - it's not something we do anywhere else and while I don't think it'd negatively affect things like composite build, I simply don't trust that functionality enough to introduce a new potential variable.

**Review by jonsie — APPROVED** [review]

**Review by srekapalli — APPROVED** [review]

**Comment by AbdulRahmanAlHamali** [comment]
Hi Rob, I noticed that the document here still refers to the old keiko repo:
https://spinnaker.io/guides/developer/service-overviews/orca/#runtime

Maybe it requires an update?

**Pull request merged**
