### PR TITLE
core: Make use of ImagesSummary endpoint

### PR DESCRIPTION
**Pull request by lwander**
Makes use of new endpoint written here: https://github.com/spinnaker/clouddriver/pull/349

Don't merge until that above PR is in.

@ttomsu, @cfieber PTAL.

### CODE REVIEW

**Comment by lwander** [comment]
@duftler - Meat Travis escaped to the mountains before looking this over

**Comment by duftler** [comment]
LGTM. Defer to @cfieber or @ajordens on merging after he has a look at the clouddriver one first.

**Comment by ttomsu** [comment]
LGTM too

**Comment by lwander** [comment]
ping @cfieber

**Comment by lwander** [comment]
Rebased

**Comment by duftler** [comment]
@ajordens or @cfieber any concerns if I merge this one?

**Comment by ajordens** [comment]
LGTM

**Pull request merged**
