### PR TITLE
A couple of queueing fixes

### PR DESCRIPTION
**Pull request by robfletcher**
- ensure pipeline queue is only checked after the status is propagated otherwise queued pipelines aren't started as the original pipeline status is incomplete
- run v2 pipelines in v2 mode from the queue

### CODE REVIEW

**Comment by robfletcher** [comment]
PTAL @ajordens

**Comment by ajordens** [comment]
Could we have fixed the ordering issue if the Order of the composite
listener was such that it always ran first?

**Comment by ajordens** [comment]
Otherwise LGTM ... I'm satisfied with being very explicit about the
ordering of listeners.

**Comment by robfletcher** [comment]
We possibly could manage the ordering with the annotations but I have to say I prefer doing it in code when it's that important.

**Pull request merged**
