### PR TITLE
core/bake: Add varFileName attribute to bake request.

### PR DESCRIPTION
**Pull request by duftler**

### CODE REVIEW

**Comment by duftler** [comment]
@tomaslin @ajordens or @cfieber please review.
We verified a week or two back that new bake request attributes will not break the internal bakery.
This pr relates to https://github.com/spinnaker/rosco/pull/131, but they can be merged in any order.

**Comment by ajordens** [comment]
Should `BakeRequest` start using @JsonAnyGetter/@JsonAnySetter and avoid the need to keep adding attributes that are just passed through to `rosco`?

**Comment by ajordens** [comment]
Otherwise this LGTM

**Comment by duftler** [comment]
I experimented with @JsonAnyGetter/@JsonAnySetter and the problem was that the property naming strategy is ignored for these 'dynamic' properties. So I'd either have to use the snake case naming for just the new dynamic properties (in deck/api callers) or mangle the names myself in the dynamic getter. Seems like that'd be less clean than just including the exact properties in `BakeRequest`. WDYT?

**Comment by ajordens** [comment]
Tough one.

I'd probably go for applying the `LowerCaseWithUnderscoresStrategy.translate()` on the `@JsonAnySetter` and avoid the need to release `orca` whenever a new bake property goes in.

I don't feel overly strong about this ... (_if we could go back in time, I'd suggest making the snake case an internal concern of our bakery and feed regular unprocessed camel-case to rosco_).

**Comment by duftler** [comment]
That's not bad. I'll make that change to the setter.

**Comment by duftler** [comment]
Done.

**Comment by ajordens** [comment]
LGTM!

**Comment by robfletcher** [comment]
This is breaking baking in AWS because we're dumping a spurious `status` property from the context into the bake request.

**Pull request merged**
