### PR TITLE
provider/amazon: use HashMap for context in DestroyAsgTask

### PR DESCRIPTION
**Pull request by anotherchrisberry**
@spinnaker/netflix-reviewers PTAL

### CODE REVIEW

**Comment by anotherchrisberry** [comment]
And in `PackageInfo`, just for good measure

**Comment by anotherchrisberry** [comment]
Recent changes to Jackson somewhere in our tiny dependency graph have caused `Map` to become an `UnmodifiableMap`, which is, um, not modifiable

**Comment by ajordens** [comment]
Honestly not a big fan of forcing HashMap all over the place, what's the level of effort to track down where the behavior change came from?

**Comment by anotherchrisberry** [comment]
Merging reluctantly so we can unblock the team depending on the task here...

**Pull request merged**
