### PR TITLE
config(metrics): best effort at pulling account, region, cloud from c…

### PR DESCRIPTION
**Pull request by dreynaud**
…ontext

This is closer to what actual tasks are doing, in particular ServerGroupCacheForceRefreshTask.

### CODE REVIEW

**Comment by robzienert** [comment]
Why not just use `orca-core`? What goes in `-common` that wouldn't have a place in `-core`?

**Comment by dreynaud** [comment]
@robzienert it's definitely possible. Since it's more of a utility thing and not particularly a "core" thing, I thought maybe we'd want to avoid polluting core. What says @robfletcher ?

**Comment by ajordens** [comment]
tbh I'd probably stash it in `core` personally.

**Comment by robfletcher** [comment]
I kinda like the idea of keeping it out of core but it's not a huge deal, I don't think

**Comment by dreynaud** [comment]
Deleted orca-common and moved `CloudProviderAware` into core

**Pull request merged**
