### PR TITLE
Invert from and to

### PR DESCRIPTION
**Pull request by gbougeard**
The source commit should be the `from` and the target commit the `to`.
If it's not in the right order, the commits list will be empty (at least when using github)

### CODE REVIEW

**Comment by tomaslin** [comment]
need to verify that this behavior is the same in stash

**Comment by gbougeard** [comment]
@tomaslin do you have any news about this?

**Comment by tomaslin** [comment]
@dzapata PTAL

**Comment by dzapata** [comment]
This is what's working for Stash currently.  I'll dig some more and see if it's flipped somewhere in the code.

**Comment by dzapata** [comment]
The stash rest api documentation (https://developer.atlassian.com/static/rest/stash/3.0.1/stash-rest.html) is not clear on this, but I just verified that 'to' = older/source commit and 'from' = newer/target commit.  If it's the reverse in GitHub (haven't verified) the proper fix may be to modify the igor service (https://github.com/spinnaker/igor) to account for this (which is what orca calls for the commit diff).

**Comment by gbougeard** [comment]
https://developer.github.com/v3/repos/commits/#compare-two-commit

**Comment by gbougeard** [comment]
I think the most confusing is the naming of `sourceCommit` and `targetCommit`. In my mind it's make more sense that `sourceCommit` is the `from` and the `targetCommit` is the `to`.

**Comment by gbougeard** [comment]
@dzapata any news about this?

**Comment by gbougeard** [comment]
With the curren implementation in igor, to retrieve the commit history you need to set as from the older commit and as to the newest. So the reverse of stash.

**Comment by dzapata** [comment]
Maybe abstract both of them out and make the igor api use 'oldest' 'newest' and each repo type implements it their way?

**Comment by gbougeard** [comment]
https://github.com/spinnaker/igor/issues/135

**Pull request closed without merging**
