### PR TITLE
fix: Resource requests on custom stage | Error: got "map", expected "string…"

### PR DESCRIPTION
**Pull request by armory-abedonik**
`manifest` field defined in `KubernetesPreconfiguredJobProperties` class has `io.kubernetes.client.openapi.models.V1Job` type. This type is defined in Kubernetes Open API models package. This package contains special JSON serializers e.g `io.kubernetes.client.custom.Quantity.QuantityAdapter`. They must be used to get correct JSON format.

### CODE REVIEW

**Review by mattgogerly — APPROVED** [review]

**Comment by mattgogerly** [comment]
@Mergifyio update

**Comment by mattgogerly** [comment]
Mind changing the commit message to be in the format? Thanks!

`fix(preconfiguredJobs): ...`

**Comment by link108** [comment]
@mergifyio backport release-1.28.x

**Comment by link108** [comment]
@mergifyio backport release-1.27.x

**Pull request merged**
