### PR TITLE
fix(stages/bakery): Fix bake stage, ensure deploymentDetails is added to context

### PR DESCRIPTION
**Pull request by christopherthielen**
The `deploymentDetails` field in the stage output was not created properly because #1597 changed the stage types for the parallel stages.  This reverts the names of the parallel stages to the basic name (without `.parallel`)

The `Parallel` static Stage Def classes are removed in favor of inline conditionals

### CODE REVIEW

**Comment by jrsquared** [comment]
sure

**Comment by robfletcher** [comment]
This puts the actual stage types back as they were before but retains the streamlining of how parallel stages are defined from https://github.com/spinnaker/orca/pull/1597.

**Comment by ajordens** [comment]
Assuming that we sanity checked the UI behaves correctly now?

**Comment by christopherthielen** [comment]
Sanity checked UI based on node quark's use

**Pull request merged**
