### PR TITLE
fix(core): Remove unsafe bool cast

### PR DESCRIPTION
**Pull request by lwander**
Undefined "strategy" can't be cast to `boolean`.

### CODE REVIEW

**Comment by lwander** [comment]
Or if any of the @spinnaker/netflix-reviewers are online and can give this a quick look. Seems that Matt is out.

**Comment by jrsquared** [comment]
LGTM, curious why there was a boolean cast there to begin with? 🤔

**Comment by lwander** [comment]
Thanks guys

**Comment by lwander** [comment]
I thought `"strategy"` was a string? e.g. `"redblack"` or `"highlander"`

**Comment by robfletcher** [comment]
Not in this case. It's a Boolean in the trigger (IIRC) that indicates if the child pipeline is a custom deploy strategy or not. You should probably do `null as Boolean ?: false`

**Comment by tomaslin** [comment]
No, this is to indicate that that pipeline is a custom strategy execution. The string you're thinking of stays in the deploy stage

**Comment by lwander** [comment]
Ah ok let me fix this

**Comment by lwander** [comment]
https://github.com/spinnaker/orca/pull/1247

**Pull request merged**
