### PR TITLE
provider/kubernetes: Cluster wide operations fix

### PR DESCRIPTION
**Pull request by lwander**
At some point I switched back from region -> namespace, breaking cluster wide ops

### CODE REVIEW

**Comment by lwander** [comment]
@duftler

**Comment by duftler** [comment]
LGTM.

**Comment by ajordens** [comment]
This seems rather difficult to read? (and probably not tested?)

**Comment by lwander** [comment]
Yeah you're right on both accounts. @duftler, can we drop `zone` here? That will at least make it a little easier to read. I'll work on tests tomorrow.

**Comment by duftler** [comment]
Would like to leave the `zones` support for a while still. If we remove it, pipelines that are still using the pre-region style will break. Could leave a todo to remove it in a month if you like.

Maybe dropping the use of the chained ternary operators will make it more readable.

**Pull request merged**
