### PR TITLE
fix(cfn): Return RUNNING if an error occurred

### PR DESCRIPTION
**Pull request by xavileon**
Force cache refreshing was a retryable task. However, it didn't return
RUNNING whenever the cache refresh failed, and thus the task failed
immediately. This patch makes the task return RUNNING whenever there's
an exception refreshing the cache so it actually retries.

### CODE REVIEW

**Comment by xavileon** [comment]
Yes, sorry as well, I missed this too :-)

**Comment by xavileon** [comment]
@spinnakerbot cherry-pick 1.16

**Comment by rampatnaik** [comment]
@spinnaker please reopen

**Comment by rampatnaik** [comment]
@spinnakerbot I have similar issues. 
Please reopen

**Pull request merged**
