### PR TITLE
fix(cfn): Fix detection of empty CloudFormation changesets

### PR DESCRIPTION
**Pull request by jaredstehler**
It seems that the status message from AWS has changed or could potentially differ. Updating to check for what I'm getting as output.

```
aws cloudformation describe-change-set --region us-east-1 --stack-name my-stack --change-set-name ChangeSet-01FE1BBN47Z1XND6QHNYC6CSRZ

{
    "Changes": [],
    "ChangeSetName": "ChangeSet-01FE1BBN47Z1XND6QHNYC6CSRZ",
    "ChangeSetId": "arn:aws:cloudformation:us-east-1:123456789012:changeSet/ChangeSet-01FE1BBN47Z1XND6QHNYC6CSRZ/5c97c64a-14aa-42c7-8343-73fbedff0e7f",
    "StackId": "arn:aws:cloudformation:us-east-1:123456789012:stack/my-stack/f015d500-8e72-11ea-a6ca-0a6641f83659",
    "StackName": "namespace-doolittle-qa",
    "Description": null,
    "Parameters": [...],
    "CreationTime": "2021-08-26T13:46:04.623000+00:00",
    "ExecutionStatus": "UNAVAILABLE",
    "Status": "FAILED",
    "StatusReason": "No updates are to be performed.",
    "NotificationARNs": [
        "arn:aws:sns:us-east-1:123456789012:ops-regional-SpinnakerCfnNotificationTopic-19Z5KZO2FTQNI"
    ],
    "RollbackConfiguration": {},
    "Capabilities": [
        "CAPABILITY_NAMED_IAM",
        "CAPABILITY_AUTO_EXPAND"
    ],
    "Tags": null,
    "ParentChangeSetId": null,
    "IncludeNestedStacks": true,
    "RootChangeSetId": null
}
```

### CODE REVIEW

**Comment by jaredstehler** [comment]
** nudge **

**Review by deverton — APPROVED** [review]

**Comment by jaredstehler** [comment]
is there a reason this can't be merged?

**Review by deverton — APPROVED** [review]

**Comment by deverton** [comment]
Looks like I don't have approver permissions so my approval doesn't count unfortunately.

**Comment by deverton** [comment]
@spinnaker/oss-approvers any chance of getting this PR merged? Looks good to me and fixes an annoyance when using Cloudformation changesets.

**Comment by dbyron-sf** [comment]
I think the PR checks were failing for some other reason...I just kicked them off again.

And I realize this has already taken forever, but I gotta ask...any chance you can add an automated test for the change?

**Comment by jaredstehler** [comment]
i can give that a shot, sure

**Comment by dbyron-sf** [comment]
Thanks @jaredstehler !

**Comment by dbyron-sf** [comment]
@mergifyio update

**Comment by jaredstehler** [comment]
reopening from personal account with mergify permissions, requested test update

https://github.com/spinnaker/orca/pull/4270

**Pull request closed without merging**
