### PR TITLE
chore(build): update Mergify config

### PR DESCRIPTION
**Pull request by mattgogerly**
Strict mode is gone.

### CODE REVIEW

**Comment by dbyron-sf** [comment]
Are the invalid mergify config errors relevant? (e.g. https://github.com/spinnaker/orca/pull/4209/checks?check_run_id=4860764992)

**Comment by mattgogerly** [comment]
> Are the invalid mergify config errors relevant? (e.g. https://github.com/spinnaker/orca/pull/4209/checks?check_run_id=4860764992)

I think that's complaining about the current config

**Review by dbyron-sf — APPROVED** [review]

**Comment by link108** [comment]
@mergifyio backport release-1.27.x release-1.26.x

**Comment by link108** [comment]
@Mergifyio backport release-1.25.x

**Pull request merged**
