### PR TITLE
fix(manifests): s/name/manifestName

### PR DESCRIPTION
**Pull request by lwander**
https://github.com/spinnaker/clouddriver/pull/2222

### CODE REVIEW

**Comment by lwander** [comment]
@andrewbackes

**Comment by andrewbackes** [comment]
In the case of using `labelSelectors`, `manifestName` will not be present. I think you will get something like this in Deck:

Error

Also, I think name is used here: https://github.com/spinnaker/orca/blob/master/orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/ManifestForceCacheRefreshTask.java

**Comment by lwander** [comment]
That's fair, but for a separate PR

**Comment by lwander** [comment]
I'm planning on having clouddriver return every manifest it attempted to modify, that orca can then refresh and monitor all at once

**Comment by lwander** [comment]
https://github.com/spinnaker/spinnaker/issues/2169

**Pull request merged**
