### PR TITLE
fix(spel): Fix assumptions made that were broke by #1892.

### PR DESCRIPTION
**Pull request by jtk54**
Fix assumptions made that were broke by #1892.

### CODE REVIEW

**Comment by jtk54** [comment]
Don't merge yet, need to add unit test.

**Comment by jtk54** [comment]
I don't know if that's the right fix yet, feels off that the webhook resp lands in `buildInfo`. Talking with Gard and Jorgen.

**Comment by ethanfrogers** [comment]
would moving the response out of `buildInfo` constitute a breaking change?

**Comment by jtk54** [comment]
I'd imagine yes, we're still breaking the contract no matter how weird it was.

**Comment by lwander** [comment]
We can always put it into another field alongside `buildInfo`, and then figure out what to do with that field later. In the end a user writing SPEL shouldn't have to reference `buildInfo` to get a webhook output.

**Comment by ethanfrogers** [comment]
yeah, that seems like a good idea. i'm not familiar with how the accessor methods work, but maybe that would be use case for one? then we can deprecate `buildInfo` once people have a change to move to the new field or the accessor method.

**Comment by jtk54** [comment]
Merging this, will address relocating the response body in a later PR.

**Comment by jervi** [comment]
I've made a shot at the first stage of the relocations in #1959. Please take a look.

**Pull request merged**
