### PR TITLE
closes spinnaker/spinnaker#897

### PR DESCRIPTION
**Pull request by drmaas**

### CODE REVIEW

**Comment by duftler** [comment]
Please use descriptive PR descriptions and commit messages.
This one could have something like:
core/bakery: Feature-flag propagation of new `instanceType` bake request attribute.

**Comment by duftler** [comment]
Please add this new attribute to the test that verifies they are not propagated to the internal Netflix bakery: https://github.com/spinnaker/orca/blob/master/orca-bakery/src/test/groovy/com/netflix/spinnaker/orca/bakery/tasks/CreateBakeTaskSpec.groovy#L637

**Comment by duftler** [comment]
LGTM after updating the unit test.
Needs a rebase.

**Comment by drmaas** [comment]
@spinnaker/reviewers

**Pull request merged**
